### ISSUE TITLE
 cannot open display: 10.0.0.102:0

### ISSUE THREAD

**Issue by lkthomas** [mbentley/docker-virt-manager#8]
docker run   -v /tmp/.X11-unix   -e DISPLAY=10.0.0.102:0 -v ~/.ssh/id_rsa:/root/.ssh/id_rsa   mbentley/virt-manager

(virt-manager:1): Gtk-WARNING **: cannot open display: 10.0.0.102:0

Any idea why? base OS: Ubuntu 14

**Comment by mbentley** [comment]
Did you directly try to run the example?:

```
docker run \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -e DISPLAY=unix$DISPLAY \
  -v ~/.ssh/id_rsa:/root/.ssh/id_rsa \
  mbentley/virt-manager
```

Typically when you're running X, it will create a socket in /tmp/.X11-unix that is named `X0` by default.  In your env vars, that number is normally set in the `$DISPLAY` env var.  By sharing `/tmp/.X11-unix` into a container using a bind mount, that allows the socket to be available inside the container.  Your bind mount for `/tmp/.X11-unix` doesn't have the host side mounted in and then your `DISPLAY` env var is an IP instead of just the socket so it looks like you might have a combination of the example running on MacOS and Linux.
