### ISSUE TITLE
Virt-manager 5.0.0

### ISSUE THREAD

**Issue by waja** [mbentley/docker-virt-manager#9]
Version 5.0.0. was [released](https://github.com/virt-manager/virt-manager/releases/tag/v5.0.0) today.

**Comment by mbentley** [comment]
Currently I am [seeing 4.1.0 in Alpine Linux edge](https://pkgs.alpinelinux.org/packages?name=virt-manager&branch=edge&repo=&arch=x86_64&origin=&flagged=&maintainer=) and [3.20](https://pkgs.alpinelinux.org/packages?name=virt-manager&branch=v3.20&repo=&arch=x86_64&origin=&flagged=&maintainer=).  Since I am just pulling the packages from Alpine Linux, I'll have to wait until they're available at least in edge before I can consume or test them.

**Comment by mbentley** [comment]
It does look like the edge version has been auto-flagged as having 5.0.0 available so hopefully it won't be too long before the package maintainer might be able to get a version in edge.

**Comment by mbentley** [comment]
[Edge](https://pkgs.alpinelinux.org/packages?name=virt-manager&branch=edge&repo=&arch=x86_64&origin=&flagged=&maintainer=) now has 5.0; will see if I can update to use edge later today or at least to do a test build.

**Comment by waja** [comment]
Looks like alpine 3.21 [is in the pipeline](https://fosstodon.org/@alpinelinux/113568293880729433). :)

**Comment by mbentley** [comment]
`latest` should have 5.0.0 in it now that Alpine 3.21 has been released.

**Comment by waja** [comment]
Uh wow! Didn't expect that 5.0.0 will make it into Alpine 3.21 so short before the release.
